### ISSUE TITLE
nodes from mni-coordinates

### ISSUE THREAD

**Issue by rschmaelzle** [aestrivex/cvu#6]
Hi all
I'd would like to visualize my connectivity data in 3d using CVU. However, I have a somewhat idiosyncratic parcellation of 10 nodes for which I have created a coorrdinate file as a 10*3 numpy-array (coordinates). I have also created a labels-txt file with 10 anatomical descriptors. Based on wiki and the buttons, I thought I can load this parcellation. Thus, I enter the load parcellation dialogue and fill out everything (new dataset, subject, subjs-dir,). I use as SUBJECT fsavg5 and the registration matrix mni152.register.dat. However, somehow nothing gets loaded. Is there maybe an example set of  coordinate/label  files that I could use as a start. Or am I totally awry? 
Best, Ralf.

**Comment by aestrivex** [comment]
It should be possible to do that. I think the problem is that CVU is not
parsing the registration matrix as intelligently as you expect; it is
expecting either a matrix file (.npy, .txt, etc) with a 4x4 affine matrix
and nothing else, but instead it got a freesurfer-formatted file with
numerous fields it didnt understand.

**Comment by rschmaelzle** [comment]
thanks so much for the quick reply. I tried using a 4X4 extracted from what I believe the right lines in mni152register.dat, and as that failed some ad hoc affine. However, i could not get it to work and did not get an error message. I put the files I work with and a screenshot [here](https://drive.google.com/open?id=0B-sCgoERRQPaTkdud1J6SXFhRkU). Thanks, Ralf.

**Comment by aestrivex** [comment]
Hi Ralf,

The problem is your ordering file where the names aren't getting parsed because the program can't figure out which hemisphere they belong to. I originally conceived of CVU as working only with surface parcellations and so it made sense to write the parser in such a way that every label has to be assigned a hemisphere. That parser still uses the same behavior in looking for labels, even with the newer "coordinates file" method of defining ROIs.

This is kind of my fault, it is documented somewhere on the wiki, but it could be implemented much more flexibly (I will leave this issue open as a reminder)

For now, I replaced the ordering file with the following:

> lh_roi_1
> rh_roi_2
> lh_roi_3
> rh_roi_4
> rh_roi_5
> lh_roi_6
> rh_roi_7
> lh_roi_8
> rh_roi_9
> lh_roi_10

which works. I randomly picked a hemisphere for the ROIs on the midline.

**Comment by rschmaelzle** [comment]
thanks! Works now! Best, Ralf.
